name: Hexo Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Setup Hexo And Deploy
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.PAGE_TOKEN }}
        run: |
          npm install hexo-cli -g
          npm install
          hexo clean
          hexo deploy
